
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vidya
 */
public class penitipan extends javax.swing.JFrame {

    /**
     * Creates new form penitipan
     */
    public penitipan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        masuk = new com.toedter.calendar.JDateChooser();
        keluar = new com.toedter.calendar.JDateChooser();
        mobil = new javax.swing.JRadioButton();
        motor = new javax.swing.JRadioButton();
        nm = new javax.swing.JTextField();
        resi = new javax.swing.JTextField();
        nopol = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        hari = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        lht = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        print = new javax.swing.JButton();
        del = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        refresh = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nama Petugas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 80, 110, 20);

        jLabel2.setText("No.Resi");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 120, 110, 20);

        jLabel3.setText("NO.Pol");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 160, 110, 20);

        jLabel4.setText("Jenis Kendaraan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 200, 110, 20);

        jLabel5.setText("Tanggal Masuk");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 240, 110, 20);

        jLabel6.setText("Tanggal Keluar");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 280, 110, 20);
        getContentPane().add(masuk);
        masuk.setBounds(130, 240, 140, 30);
        getContentPane().add(keluar);
        keluar.setBounds(130, 280, 140, 30);

        mobil.setBackground(new java.awt.Color(255, 153, 153));
        buttonGroup1.add(mobil);
        mobil.setText("Mobil");
        getContentPane().add(mobil);
        mobil.setBounds(120, 200, 90, 23);

        motor.setBackground(new java.awt.Color(255, 153, 153));
        buttonGroup1.add(motor);
        motor.setText("Motor");
        motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorActionPerformed(evt);
            }
        });
        getContentPane().add(motor);
        motor.setBounds(220, 200, 53, 23);

        nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmActionPerformed(evt);
            }
        });
        getContentPane().add(nm);
        nm.setBounds(130, 80, 140, 30);
        getContentPane().add(resi);
        resi.setBounds(130, 120, 140, 30);
        getContentPane().add(nopol);
        nopol.setBounds(130, 160, 140, 30);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        jLabel7.setText("Penitipan Mobil dan Motor");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 10, 300, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 830, 60);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 300, 260);

        tblData.setBackground(new java.awt.Color(255, 153, 153));
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NamaPetugas", "NoResi", "NoPol", "JenKendaraan", "tglmasuk", "tglkeluar", "harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDataMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(320, 80, 490, 240);

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));
        jPanel3.setLayout(null);

        jLabel8.setText("Jumlah Hari");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 40, 110, 20);
        jPanel3.add(hari);
        hari.setBounds(140, 30, 140, 30);

        jLabel9.setText("Harga");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 90, 110, 20);

        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        jPanel3.add(harga);
        harga.setBounds(140, 80, 140, 30);

        lht.setText("Lihat");
        lht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lhtActionPerformed(evt);
            }
        });
        jPanel3.add(lht);
        lht.setBounds(140, 120, 140, 20);

        jLabel10.setText("Masukkan jumlah hari untuk melihat harga");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 10, 240, 20);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 340, 300, 170);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(320, 440, 110, 30);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(570, 440, 110, 30);

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(700, 440, 110, 30);

        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        getContentPane().add(del);
        del.setBounds(450, 440, 110, 30);

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setLayout(null);

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel4.add(refresh);
        refresh.setBounds(380, 280, 110, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(310, 70, 520, 330);

        jPanel5.setLayout(null);
        getContentPane().add(jPanel5);
        jPanel5.setBounds(310, 410, 510, 100);

        jPanel6.setLayout(null);
        getContentPane().add(jPanel6);
        jPanel6.setBounds(310, 410, 520, 100);

        jPanel8.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8);
        jPanel8.setBounds(310, 410, 520, 100);

        setBounds(0, 0, 840, 552);
    }// </editor-fold>//GEN-END:initComponents

    private void motorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motorActionPerformed

    private void nmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String kend="";
        if(mobil.isSelected()){
            kend="mobil";
        }else{
            kend="motor";
        }
       
        if(nm.getText().equals("")||
        resi.getText().equals("")||
        nopol.getText().equals("")||
        kend.equals("")||
       masuk.equals("") ||
       keluar.equals("")||
       harga.getText().equals("")){
        JOptionPane.showMessageDialog(this, "lengkapi data!","Error", JOptionPane.WARNING_MESSAGE);
    }else{
             String SQL="INSERT INTO tb_data (NamaPetugas,NoResi,NoPol,JenKendaraan,tglmasuk,tglkeluar,harga)"
                     +"VALUES('"+nm.getText()+"',"
                       + "'"+resi.getText()+"','"
                       +"','"+nopol.getText()+"','"
                       +"',"+kend+"','"
                       + "','"+masuk+"','"
                       +"',"+keluar+"',"
                       +"','"+harga.getText()+"')";
                               int status = KoneksiDB.execute(SQL);
                               if(status== 1){
                                   JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                                   selectData();
                               }else{
                                   JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
                               }
                
         
            
        }                         
// TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        int baris = tblData.getSelectedRow();
        if(baris != -1){
            String NIS = tblData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_data WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==0){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_delActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void lhtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lhtActionPerformed
        int htg = Integer.parseInt(hari.getText());
        int jml = 0;
        
        jml = htg*3000;
        harga.setText(String.valueOf(jml));
// TODO add your handling code here:
    }//GEN-LAST:event_lhtActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       nm.setText("");
        resi.setText("");
        nopol.setText("");
        buttonGroup1.clearSelection();
        harga.setText("");
       
        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        selectData();
// TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        MessageFormat header = new MessageFormat("Penitipan Mobil dan Motor");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}         ");
        try{
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer,true, null, true, null);
        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
// TODO add your handling code here:
    }//GEN-LAST:event_printActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
       
    }//GEN-LAST:event_tblDataMouseClicked

    private void tblDataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDataMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penitipan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penitipan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penitipan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penitipan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penitipan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton del;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField hari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser keluar;
    private javax.swing.JButton lht;
    private com.toedter.calendar.JDateChooser masuk;
    private javax.swing.JRadioButton mobil;
    private javax.swing.JRadioButton motor;
    private javax.swing.JTextField nm;
    private javax.swing.JTextField nopol;
    private javax.swing.JButton print;
    private javax.swing.JButton refresh;
    private javax.swing.JTextField resi;
    private javax.swing.JButton save;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
      String kolom[]={"NamaPetugas","NoResi","NoPol","JenKendaraan","tglmasuk","tglkeluar","harga"};
                DefaultTableModel dtm = new DefaultTableModel(null, kolom);
                String SQL = "SELECT * FROM tb_data";
                ResultSet rs = KoneksiDB.executeQuery(SQL);
                try{
                    while(rs.next()){
                        String NamaPetugas = rs.getString(1);
                        String NoResi =rs.getString(2);
                        String NoPol = rs.getString(3);
                        String JenKendaraan ="";
                        if("Mobil".equals(rs.getString(4))){
                           JenKendaraan = "Mobil";
                        }else{
                           JenKendaraan = "Motor";
                        }
                        String tglmasuk = rs.getString(5);
                        String tglkeluar = rs.getString(6);
                        String harga = rs.getString(7);
                        String data[] = {NamaPetugas, NoResi, NoPol, JenKendaraan,tglmasuk, tglkeluar, harga};
                        dtm.addRow(data);
                    }
                }catch(SQLException ex){
                    Logger.getLogger(penitipan.class.getName()).log(Level.SEVERE,null, ex);
                }
                tblData.setModel(dtm);
        //To change body of generated methods, choose Tools | Templates.
    }
}
